# Manipulation and Cleaning Data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Stats survey.csv')

In [3]:
df.head()

,Timestamp,Your Sex?,Your Matric (grade 12) Average/ GPA (in %),What year were you in last year (2023) ?,What faculty does your degree fall under?,Your 2023 academic year average/GPA in % (Ignore if you are 2024 1st year student),Your Accommodation Status Last Year (2023),Monthly Allowance in 2023,Were you on scholarship/bursary in 2023?,Additional amount of studying (in hrs) per week,How often do you go out partying/socialising during the week?,"On a night out, how many alcoholic drinks do you consume?","How many classes do you miss per week due to alcohol reasons, (i.e: being hungover or too tired?)",How many modules have you failed thus far into your studies?,Are you currently in a romantic relationship?,Do your parents approve alcohol consumption?,How strong is your relationship with your parent/s?
0,2024/03/07 5:12:01 pm EET,Female,76.0,2nd Year,Arts & Social Sciences,72.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,8+,Only weekends,8+,3,0,Yes,Yes,Very close
1,2024/03/07 5:12:08 pm EET,Male,89.0,2nd Year,Economic & Management Sciences,75.0,Private accommodation/ stay with family/friends,R 7001 - R 8000,"Yes (NSFAS, etc...)",8+,Only weekends,3-5,4+,0,No,Yes,Very close
2,2024/03/07 5:12:25 pm EET,Male,76.0,1st Year,AgriSciences,55.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,2,8+,3,0,No,Yes,Very close
3,2024/03/07 5:12:28 pm EET,Male,89.0,2nd Year,Engineering,84.0,Private accommodation/ stay with family/friends,R 6001 - R 7000,No,3-5,3,8+,2,0,Yes,Yes,Very close
4,2024/03/07 5:13:00 pm EET,Female,74.0,2nd Year,Arts & Social Sciences,52.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,Only weekends,5-8,1,3,No,Yes,Fair

In [4]:
df.drop(['Timestamp'], axis = 1, inplace = True)

In [5]:
df.head()

,Your Sex?,Your Matric (grade 12) Average/ GPA (in %),What year were you in last year (2023) ?,What faculty does your degree fall under?,Your 2023 academic year average/GPA in % (Ignore if you are 2024 1st year student),Your Accommodation Status Last Year (2023),Monthly Allowance in 2023,Were you on scholarship/bursary in 2023?,Additional amount of studying (in hrs) per week,How often do you go out partying/socialising during the week?,"On a night out, how many alcoholic drinks do you consume?","How many classes do you miss per week due to alcohol reasons, (i.e: being hungover or too tired?)",How many modules have you failed thus far into your studies?,Are you currently in a romantic relationship?,Do your parents approve alcohol consumption?,How strong is your relationship with your parent/s?
0,Female,76.0,2nd Year,Arts & Social Sciences,72.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,8+,Only weekends,8+,3,0,Yes,Yes,Very close
1,Male,89.0,2nd Year,Economic & Management Sciences,75.0,Private accommodation/ stay with family/friends,R 7001 - R 8000,"Yes (NSFAS, etc...)",8+,Only weekends,3-5,4+,0,No,Yes,Very close
2,Male,76.0,1st Year,AgriSciences,55.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,2,8+,3,0,No,Yes,Very close
3,Male,89.0,2nd Year,Engineering,84.0,Private accommodation/ stay with family/friends,R 6001 - R 7000,No,3-5,3,8+,2,0,Yes,Yes,Very close
4,Female,74.0,2nd Year,Arts & Social Sciences,52.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,Only weekends,5-8,1,3,No,Yes,Fair

## outlier

In [ ]:
def handling_outlier(df: pd.df, nums_columns):
    for every in df:
        q1 = df[every].quantile(q1)

In [11]:
nan_accom = df['Your Accommodation Status Last Year (2023)'].isna()
print(nan_accom)

print(df.loc[nan_accom])
filled_accom = nan_accom.fillna('unknown')
filled_accom

0      False
1      False
2      False
3      False
4      False
       ...
401    False
402    False
403    False
404    False
405    False
Name: Your Accommodation Status Last Year (2023), Length: 406, dtype: bool
    Your Sex?  Your Matric (grade 12) Average/ GPA (in %)  \
8        Male                                        89.0
9        Male                                        83.0
10     Female                                        75.0
14       Male                                        78.0
76     Female                                        76.0
77     Female                                        87.0
114    Female                                        83.0
115    Female                                        84.0
153    Female                                        85.0
163    Female                                        69.0
171    Female                                        73.0
180      Male                                        79.0
224       NaN                                         NaN
232       NaN                                         NaN
300      Male                                        76.0
302      Male                                        79.0
337      Male                                        68.0
343    Female                                        78.0
351    Female                                        76.0
352    Female                                        86.0
374    Female                                        88.0
382    Female                                        76.0
400      Male                                        85.0

    What year were you in last year (2023) ?  \
8                                        NaN
9                                        NaN
10                                       NaN
14                                       NaN
76                                  2nd Year
77                                       NaN
114                                 1st Year
115                                      NaN
153                                      NaN
163                                      NaN
171                                      NaN
180                                      NaN
224                                      NaN
232                                      NaN
300                                      NaN
302                                      NaN
337                                 1st Year
343                                      NaN
351                                      NaN
352                                      NaN
374                                      NaN
382                                      NaN
400                                      NaN

    What faculty does your degree fall under?  \
8                                 Engineering
9                                     Science
10                               AgriSciences
14                                    Science
76                                        Law
77                                    Science
114            Economic & Management Sciences
115            Economic & Management Sciences
153                    Arts & Social Sciences
163            Economic & Management Sciences
171            Economic & Management Sciences
180                               Engineering
224                                       NaN
232                                       NaN
300                    Arts & Social Sciences
302            Economic & Management Sciences
337                              AgriSciences
343            Economic & Management Sciences
351            Economic & Management Sciences
352                               Engineering
374                                       Law
382                    Arts & Social Sciences
400                    Arts & Social Sciences

     Your 2023 academic year average/GPA in % (Ignore if you are 2024 1st year student)  \
8                                                  NaN
9                                                  NaN
10                                                 NaN
14                                                 NaN
76                                                60.0
77                                                 NaN
114                                                NaN
115                                                NaN
153                                                NaN
163                                                NaN
171                                                NaN
180                                                NaN
224                                                NaN
232                                                NaN
300                                                NaN
302                                                NaN
337                                                NaN
343                                                NaN
351                                               60.0
352                                                NaN
374                                                NaN
382                                                NaN
400                                                NaN

    Your Accommodation Status Last Year (2023) Monthly Allowance in 2023  \
8                                          NaN           R 5001 - R 6000
9                                          NaN           R 6001 - R 7000
10                                         NaN            R 4001- R 5000
14                                         NaN                       NaN
76                                         NaN            R 4001- R 5000
77                                         NaN                       NaN
114                                        NaN           R 6001 - R 7000
115                                        NaN                       NaN
153                                        NaN                       NaN
163                                        NaN                       NaN
171                                        NaN            R 4001- R 5000
180                                        NaN           R 6001 - R 7000
224                                        NaN                       NaN
232                                        NaN                       NaN
300                                        NaN            R 4001- R 5000
302                                        NaN           R 6001 - R 7000
337                                        NaN            R 4001- R 5000
343                                        NaN                       NaN
351                                        NaN           R 7001 - R 8000
352                                        NaN           R 6001 - R 7000
374                                        NaN            R 4001- R 5000
382                                        NaN           R 6001 - R 7000
400                                        NaN           R 5001 - R 6000

    Were you on scholarship/bursary in 2023?  \
8                                         No
9                                         No
10                                        No
14                                       NaN
76                                        No
77                                       NaN
114                                       No
115                                      NaN
153                                       No
163                                       No
171                                       No
180                                      NaN
224                                      NaN
232                                      NaN
300                                       No
302                                       No
337                                       No
343                                      NaN
351                                       No
352                                       No
374                                       No
382                                      NaN
400                                       No

    Additional amount of studying (in hrs) per week  \
8                                                8+
9                                               3-5
10                                              5-8
14                                              3-5
76                                              1-3
77                                               8+
114                                             1-3
115                                               0
153                                             1-3
163                                             3-5
171                                             1-3
180                                             3-5
224                                             NaN
232                                             NaN
300                                             1-3
302                                             5-8
337                                              8+
343                                              8+
351                                             3-5
352                                             3-5
374                                             1-3
382                                             3-5
400                                             3-5

    How often do you go out partying/socialising during the week?   \
8                                        Only weekends
9                                                    3
10                                                   2
14                                                   2
76                                                   3
77                                       Only weekends
114                                      Only weekends
115                                                  3
153                                                  1
163                                                  1
171                                                  1
180                                                  0
224                                                NaN
232                                                NaN
300                                                  1
302                                                  3
337                                      Only weekends
343                                                  1
351                                                  3
352                                                  1
374                                                  3
382                                                  1
400                                      Only weekends

    On a night out, how many alcoholic drinks do you consume?  \
8                                                  3-5
9                                                  5-8
10                                                 5-8
14                                                 5-8
76                                                 5-8
77                                                 1-3
114                                                5-8
115                                                5-8
153                                                3-5
163                                                1-3
171                                                5-8
180                                                  0
224                                                NaN
232                                                NaN
300                                                 8+
302                                                5-8
337                                                 8+
343                                                1-3
351                                                3-5
352                                                 8+
374                                                 8+
382                                                  0
400                                                3-5

    How many classes do you miss per week due to alcohol reasons, (i.e: being hungover or too tired?)  \
8                                                    0
9                                                   4+
10                                                   0
14                                                   0
76                                                   2
77                                                   0
114                                                  0
115                                                  0
153                                                  0
163                                                  0
171                                                  0
180                                                  0
224                                                NaN
232                                                NaN
300                                                  1
302                                                  2
337                                                 4+
343                                                  0
351                                                  2
352                                                  0
374                                                  2
382                                                  0
400                                                  0

    How many modules have you failed thus far into your studies?  \
8                                                  NaN
9                                                    0
10                                                   0
14                                                   0
76                                                   0
77                                                   0
114                                                  0
115                                                  0
153                                                  0
163                                                  0
171                                                  0
180                                                  0
224                                                NaN
232                                                NaN
300                                                  0
302                                                  0
337                                                 4+
343                                                  0
351                                                  0
352                                                  0
374                                                  0
382                                                  0
400                                                  0

    Are you currently in a romantic relationship?  \
8                                              No
9                                              No
10                                             No
14                                             No
76                                             No
77                                             No
114                                           Yes
115                                            No
153                                            No
163                                           Yes
171                                            No
180                                            No
224                                           NaN
232                                           NaN
300                                           Yes
302                                            No
337                                            No
343                                           Yes
351                                           Yes
352                                            No
374                                            No
382                                           Yes
400                                            No

    Do your parents approve alcohol consumption?  \
8                                            Yes
9                                            Yes
10                                           Yes
14                                           Yes
76                                           Yes
77                                           Yes
114                                          Yes
115                                          Yes
153                                           No
163                                          Yes
171                                          Yes
180                                          Yes
224                                          NaN
232                                          NaN
300                                          Yes
302                                          Yes
337                                          Yes
343                                          Yes
351                                          Yes
352                                          Yes
374                                          Yes
382                                          Yes
400                                          Yes

    How strong is your relationship with your parent/s?
8                                           Very close
9                                                Close
10                                               Close
14                                          Very close
76                                          Very close
77                                          Very close
114                                               Fair
115                                              Close
153                                              Close
163                                         Very close
171                                         Very close
180                                              Close
224                                                NaN
232                                                NaN
300                                         Very close
302                                              Close
337                                         Very close
343                                              Close
351                                              Close
352                                         Very close
374                                              Close
382                                         Very close
400                                         Very close

0      False
1      False
2      False
3      False
4      False
       ...
401    False
402    False
403    False
404    False
405    False
Name: Your Accommodation Status Last Year (2023), Length: 406, dtype: bool